### ISSUE TITLE
About visualization

### ISSUE THREAD

**Issue by StevenZzz07** [gmum/3d-point-clouds-autocomplete#1]
Hi, first thanks for your inspiring work! Point cloud rendering figures in your paper are very beautiful as follows. How do you draw it? Using open3d, meshlab or other programmes?

Thanks!
![image](https://user-images.githubusercontent.com/56421441/110418239-252b1500-80d2-11eb-9208-8fbc6dc1be8e.png)

**Comment by przem85** [comment]
Such visualizations can be made in several technologies. Images in the paper was created by mayavi https://docs.enthought.com/mayavi/mayavi/
```python
import numpy as np    
from mayavi import mlab 
...
f = mlab.figure(fgcolor=(0., 0., 0.), bgcolor=(1, 1, 1), size=(1000,1000))
mlab.view(azimuth=10, elevation=90, figure=f)
pts = mlab.points3d(X_part1[:,0], X_part1[:,1], X_part1[:,2], color=(0.2, 0.4, 0.5),  scale_factor=0.02)
pts = mlab.points3d(X_part2[:,0], X_part2[:,1], X_part2[:,2], color=(0.2, 0.1, 0.1),  scale_factor=0.02)
mlab.show()
```

**Comment by StevenZzz07** [comment]
Thanks for your detailed instruction! I will try it myself!
