### ISSUE TITLE
Train on custom data

### ISSUE THREAD

**Issue by davodogster** [gmum/3d-point-clouds-autocomplete#3]
Hi has anyone been able to train HyperPocket on their own custom dataset? If so, which categories and how well did it perform? Which part of the code needs to be modified? I want to train it to do completion of dense pointclouds of individual trees. Do you think it will work well and how many trees will I need? Can I train it from scratch or will I need to use transfer learning?

**Comment by ArturKasymov** [comment]
Hi @davodogster, 
you can train the model on any class of objects. The quality depends on the number of objects and their shape complexity. 1000 samples will be enough for probably any category of objects, moreover, if most of them have similar shapes you can use less. 

It will be better to train from scratch. To do this you need to create your dataset class ([example](https://github.com/gmum/3d-point-clouds-autocomplete/blob/master/datasets/real_data.py)) and then replace this line:
`train_dataset, val_dataset_dict, test_dataset_dict = get_datasets(config['dataset'])  # core/main.py:85`
with your dataset definition. The only requirement is to scale and place your point clouds in [-1, 1]³ (like in the example above).

If you have got any other questions about implementation, feel free to contact me by email: art.kasymov@gmail.com.

**Comment by davodogster** [comment]
@ArturKasymov Thank you very much for your reply. I sent you an email a few days ago with the subject Tree Point Cloud Completion. Cheers, Sam
